- name: Create mkdir
  block:
    - name: 创建目录/usr/java
      shell: |
        mkdir -p /usr/java/
        mkdir -p /usr/share/java/
      when: not ansible_facts['file_exists'] | default(false)

#- name: bak
#  shell: |
#    mv /usr/java/jdk1.8.0_144/jre/lib/security/local_policy.jar     /usr/java/jdk1.8.0_144/jre/lib/security/local_policy.jar_bak
#    mv /usr/java/jdk1.8.0_144/jre/lib/security/US_export_policy.jar    /usr/java/jdk1.8.0_144/jre/lib/security/US_export_policy.jar_bak


#- name: Copy
#  copy:
#    src: "{{ item.src }}"
#    dest: "{{ item.dest }}"
#  with_items:
#    - { src: "mysql-connector-java.jar", dest: "/usr/share/java" }
#    - { src: "local_policy.jar", dest: "/usr/java/jdk1.8.0_144/jre/lib/security/" }
#    - { src: "US_export_policy.jar", dest: "/usr/java/jdk1.8.0_144/jre/lib/security/" }

- name: 解压jdk
  unarchive:
    src: jdk1.8.0_144.tar.gz
    dest: /usr/java
- name: 环境变量修改
  blockinfile:
    path: /etc/profile
    block: |
      export JAVA_HOME=/usr/java/jdk1.8.0_144
      export PATH=$JAVA_HOME/bin:$PATH
      CLASSPATH=.:$JAVA_HOME/lib/dt.jar:$JAVA_HOME/lib/tools.jar
- name: 环境变量
  shell: | 
    source /etc/profile
    which java
  register: jdk

- name: debug JDK
  debug:
    msg: "{{ jdk.stdout }}"  
# var: jdk.stdout


- name: bak
  shell: |
    mv /usr/java/jdk1.8.0_144/jre/lib/security/local_policy.jar     /usr/java/jdk1.8.0_144/jre/lib/security/local_policy.jar_bak
    mv /usr/java/jdk1.8.0_144/jre/lib/security/US_export_policy.jar    /usr/java/jdk1.8.0_144/jre/lib/security/US_export_policy.jar_bak


- name: Copy
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: "mysql-connector-java.jar", dest: "/usr/share/java" }
    - { src: "local_policy.jar", dest: "/usr/java/jdk1.8.0_144/jre/lib/security/" }
    - { src: "US_export_policy.jar", dest: "/usr/java/jdk1.8.0_144/jre/lib/security/" }
